#! /usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use dwalker109\Battle\CliBattleCommand;

$app = new Application;

$app->add(new CliBattleCommand());

$app->run();