#! /usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use dwalker109\Battle\CliBattleCommand;

$app = new Application;
$command = new CliBattleCommand();

$app->add($command);
$app->setDefaultCommand($command->getName());

$app->run();